### ISSUE TITLE
Enable addition of same book to multiple users

### ISSUE THREAD

**Issue by ann-russo** [aurusova/book-tracker#19]
Es sollte möglich sein, dass beliebig viele Nutzer dasselbe Buch zu ihrer Liste hinzufügen können.

Aktuell kommt die Fehlermeldung "book already exists in DB"

**Comment by fpanek** [comment]
see:
https://github.com/aurusova/book-tracker/commit/dbdca24f9ffc315f0015aef9a1b0fd01504d987c
