### ISSUE TITLE
Feature: Modify Book List Entries

### ISSUE THREAD

**Issue by ann-russo** [aurusova/book-tracker#5]
Three main functions:
1. **Edit book entry**: Change status, enter number of pages, start & finish date, notes, score
2. Changing the status **moves the book entry** to the corresponding status tab
3. **Delete book entry**: book must be removed from user’s list

Each book contains a reference to its book details page (book/:isbn).

**Comment by fpanek** [comment]
added functionality to update the following parametrs:
                status: req.body.status,
                author: req.body.author,
                year: req.body.year,
                description: req.body.description,
                genre: req.body.genre,
                isbn: req.body.isbn,
                noofpages: req.body.noofpages,
                cover: req.body.cover,
                public: req.body.public,
                language: req.body.language
